from fastapi import APIRouter, Depends, HTTPException, status
import uuid
from typing import List
from pydantic import BaseModel
from datetime import datetime
from ..models.system_documents import DocTypeEnum, DocStatusEnum
from ..services.documentation import DocumentationService

router = APIRouter(prefix="/projects/{project_id}/documents", tags=["documentation"])

class DocumentResponse(BaseModel):
    id: uuid.UUID
    project_id: uuid.UUID
    title: str
    content: str
    doc_type: DocTypeEnum
    status: DocStatusEnum
    last_updated: datetime

@router.get("", response_model=List[DocumentResponse])
async def get_documents(project_id: uuid.UUID):
    """
    Returns the system documents for a project.
    """
    # Stub: Normally we'd query the database.
    # We will return the mocked drafts.
    return [
        DocumentResponse(
            id=uuid.uuid4(),
            project_id=project_id,
            title="Executive Summary",
            content="# Executive Summary\n\nThis is a mock draft generated by the AI.",
            doc_type=DocTypeEnum.summary,
            status=DocStatusEnum.draft,
            last_updated=datetime.utcnow()
        ),
        DocumentResponse(
            id=uuid.uuid4(),
            project_id=project_id,
            title="Folder Structure",
            content="# Folder Structure\n\n- `/src`: Source code.",
            doc_type=DocTypeEnum.structure,
            status=DocStatusEnum.draft,
            last_updated=datetime.utcnow()
        ),
        DocumentResponse(
            id=uuid.uuid4(),
            project_id=project_id,
            title="Component Architecture",
            content="# Component Architecture\n\nThe system consists of a Next.js frontend and a FastAPI backend.",
            doc_type=DocTypeEnum.architecture,
            status=DocStatusEnum.draft,
            last_updated=datetime.utcnow()
        )
    ]

@router.post("/generate", response_model=List[DocumentResponse])
async def generate_drafts(project_id: uuid.UUID):
    """
    Triggers the generation of the baseline architectural documents.
    """
    service = DocumentationService(str(project_id))
    
    # Mocking the ingestion report
    mock_report = {
        "detected_stack": {"languages": ["Python", "TypeScript"]},
        "files_scanned": 150
    }
    
    docs = await service.generate_drafts(mock_report)
    
    # Return as response models
    return [
        DocumentResponse(
            id=doc.id,
            project_id=doc.project_id,
            title=doc.title,
            content=doc.content,
            doc_type=doc.doc_type,
            status=doc.status,
            last_updated=doc.last_updated
        ) for doc in docs
    ]

class DocumentUpdateRequest(BaseModel):
    content: str
    status: DocStatusEnum

@router.put("/{doc_id}", response_model=DocumentResponse)
async def update_document(project_id: uuid.UUID, doc_id: uuid.UUID, req: DocumentUpdateRequest):
    """
    Updates the content and status of a document (e.g., publishing a draft).
    """
    # Stub: Normally we'd update the DB. We'll return a mocked updated response.
    return DocumentResponse(
        id=doc_id,
        project_id=project_id,
        title="Updated Document",
        content=req.content,
        doc_type=DocTypeEnum.summary, # Mocked
        status=req.status,
        last_updated=datetime.utcnow()
    )
